// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applied_state.sql

package storage

import (
	"context"
)

const getAppliedState = `-- name: GetAppliedState :one
SELECT status_emoji, status_text, presence, source, applied_at
FROM applied_state
WHERE id = 1
`

type GetAppliedStateRow struct {
	StatusEmoji string
	StatusText  string
	Presence    string
	Source      string
	AppliedAt   int64
}

func (q *Queries) GetAppliedState(ctx context.Context) (GetAppliedStateRow, error) {
	row := q.db.QueryRowContext(ctx, getAppliedState)
	var i GetAppliedStateRow
	err := row.Scan(
		&i.StatusEmoji,
		&i.StatusText,
		&i.Presence,
		&i.Source,
		&i.AppliedAt,
	)
	return i, err
}

const setAppliedState = `-- name: SetAppliedState :exec
UPDATE applied_state
SET status_emoji = ?,
    status_text  = ?,
    presence     = ?,
    source       = ?,
    applied_at   = unixepoch()
WHERE id = 1
`

type SetAppliedStateParams struct {
	StatusEmoji string
	StatusText  string
	Presence    string
	Source      string
}

func (q *Queries) SetAppliedState(ctx context.Context, arg SetAppliedStateParams) error {
	_, err := q.db.ExecContext(ctx, setAppliedState,
		arg.StatusEmoji,
		arg.StatusText,
		arg.Presence,
		arg.Source,
	)
	return err
}
