// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meeting_patterns.sql

package storage

import (
	"context"
)

const deleteMeetingPattern = `-- name: DeleteMeetingPattern :execrows
DELETE FROM meeting_patterns WHERE id = ?
`

func (q *Queries) DeleteMeetingPattern(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMeetingPattern, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertMeetingPattern = `-- name: InsertMeetingPattern :one
INSERT INTO meeting_patterns (title_pattern, status_emoji, status_text, presence, priority)
VALUES (?, ?, ?, ?, ?)
RETURNING id, title_pattern, status_emoji, status_text, presence, priority, created_at
`

type InsertMeetingPatternParams struct {
	TitlePattern string
	StatusEmoji  string
	StatusText   string
	Presence     string
	Priority     int64
}

func (q *Queries) InsertMeetingPattern(ctx context.Context, arg InsertMeetingPatternParams) (MeetingPattern, error) {
	row := q.db.QueryRowContext(ctx, insertMeetingPattern,
		arg.TitlePattern,
		arg.StatusEmoji,
		arg.StatusText,
		arg.Presence,
		arg.Priority,
	)
	var i MeetingPattern
	err := row.Scan(
		&i.ID,
		&i.TitlePattern,
		&i.StatusEmoji,
		&i.StatusText,
		&i.Presence,
		&i.Priority,
		&i.CreatedAt,
	)
	return i, err
}

const listMeetingPatterns = `-- name: ListMeetingPatterns :many
SELECT id, title_pattern, status_emoji, status_text, presence, priority, created_at
FROM meeting_patterns
ORDER BY priority DESC, id ASC
`

func (q *Queries) ListMeetingPatterns(ctx context.Context) ([]MeetingPattern, error) {
	rows, err := q.db.QueryContext(ctx, listMeetingPatterns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeetingPattern{}
	for rows.Next() {
		var i MeetingPattern
		if err := rows.Scan(
			&i.ID,
			&i.TitlePattern,
			&i.StatusEmoji,
			&i.StatusText,
			&i.Presence,
			&i.Priority,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
