// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

type AppliedState struct {
	ID          int64
	StatusEmoji string
	StatusText  string
	Presence    string
	Source      string
	AppliedAt   int64
}

type MeetingPattern struct {
	ID           int64
	TitlePattern string
	StatusEmoji  string
	StatusText   string
	Presence     string
	Priority     int64
	CreatedAt    int64
}

type Override struct {
	ID          int64
	ExpiresAt   int64
	StatusEmoji string
	StatusText  string
	Presence    string
	CreatedAt   int64
}

type ScheduleRule struct {
	ID          int64
	DaysOfWeek  int64
	StartMinute int64
	EndMinute   int64
	StatusEmoji string
	StatusText  string
	Presence    string
	Priority    int64
	CreatedAt   int64
	UpdatedAt   int64
}
