// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: overrides.sql

package storage

import (
	"context"
)

const clearOverrides = `-- name: ClearOverrides :execrows
DELETE FROM overrides
`

func (q *Queries) ClearOverrides(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearOverrides)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredOverrides = `-- name: DeleteExpiredOverrides :execrows
DELETE FROM overrides WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredOverrides(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredOverrides, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOverride = `-- name: DeleteOverride :execrows
DELETE FROM overrides WHERE id = ?
`

func (q *Queries) DeleteOverride(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOverride, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertOverride = `-- name: InsertOverride :one
INSERT INTO overrides (expires_at, status_emoji, status_text, presence)
VALUES (?, ?, ?, ?)
RETURNING id, expires_at, status_emoji, status_text, presence, created_at
`

type InsertOverrideParams struct {
	ExpiresAt   int64
	StatusEmoji string
	StatusText  string
	Presence    string
}

func (q *Queries) InsertOverride(ctx context.Context, arg InsertOverrideParams) (Override, error) {
	row := q.db.QueryRowContext(ctx, insertOverride,
		arg.ExpiresAt,
		arg.StatusEmoji,
		arg.StatusText,
		arg.Presence,
	)
	var i Override
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.StatusEmoji,
		&i.StatusText,
		&i.Presence,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveOverrides = `-- name: ListActiveOverrides :many
SELECT id, expires_at, status_emoji, status_text, presence, created_at
FROM overrides
WHERE expires_at > ?
ORDER BY created_at DESC
`

func (q *Queries) ListActiveOverrides(ctx context.Context, expiresAt int64) ([]Override, error) {
	rows, err := q.db.QueryContext(ctx, listActiveOverrides, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Override{}
	for rows.Next() {
		var i Override
		if err := rows.Scan(
			&i.ID,
			&i.ExpiresAt,
			&i.StatusEmoji,
			&i.StatusText,
			&i.Presence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
