// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule_rules.sql

package storage

import (
	"context"
)

const deleteScheduleRule = `-- name: DeleteScheduleRule :execrows
DELETE FROM schedule_rules WHERE id = ?
`

func (q *Queries) DeleteScheduleRule(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteScheduleRule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getScheduleRule = `-- name: GetScheduleRule :one
SELECT id, days_of_week, start_minute, end_minute, status_emoji, status_text, presence, priority, created_at, updated_at
FROM schedule_rules
WHERE id = ?
`

func (q *Queries) GetScheduleRule(ctx context.Context, id int64) (ScheduleRule, error) {
	row := q.db.QueryRowContext(ctx, getScheduleRule, id)
	var i ScheduleRule
	err := row.Scan(
		&i.ID,
		&i.DaysOfWeek,
		&i.StartMinute,
		&i.EndMinute,
		&i.StatusEmoji,
		&i.StatusText,
		&i.Presence,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertScheduleRule = `-- name: InsertScheduleRule :one
INSERT INTO schedule_rules (days_of_week, start_minute, end_minute, status_emoji, status_text, presence, priority)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, days_of_week, start_minute, end_minute, status_emoji, status_text, presence, priority, created_at, updated_at
`

type InsertScheduleRuleParams struct {
	DaysOfWeek  int64
	StartMinute int64
	EndMinute   int64
	StatusEmoji string
	StatusText  string
	Presence    string
	Priority    int64
}

func (q *Queries) InsertScheduleRule(ctx context.Context, arg InsertScheduleRuleParams) (ScheduleRule, error) {
	row := q.db.QueryRowContext(ctx, insertScheduleRule,
		arg.DaysOfWeek,
		arg.StartMinute,
		arg.EndMinute,
		arg.StatusEmoji,
		arg.StatusText,
		arg.Presence,
		arg.Priority,
	)
	var i ScheduleRule
	err := row.Scan(
		&i.ID,
		&i.DaysOfWeek,
		&i.StartMinute,
		&i.EndMinute,
		&i.StatusEmoji,
		&i.StatusText,
		&i.Presence,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScheduleRules = `-- name: ListScheduleRules :many
SELECT id, days_of_week, start_minute, end_minute, status_emoji, status_text, presence, priority, created_at, updated_at
FROM schedule_rules
ORDER BY priority DESC, id ASC
`

func (q *Queries) ListScheduleRules(ctx context.Context) ([]ScheduleRule, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleRule{}
	for rows.Next() {
		var i ScheduleRule
		if err := rows.Scan(
			&i.ID,
			&i.DaysOfWeek,
			&i.StartMinute,
			&i.EndMinute,
			&i.StatusEmoji,
			&i.StatusText,
			&i.Presence,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduleRule = `-- name: UpdateScheduleRule :one
UPDATE schedule_rules
SET days_of_week = ?,
    start_minute = ?,
    end_minute   = ?,
    status_emoji = ?,
    status_text  = ?,
    presence     = ?,
    priority     = ?,
    updated_at   = unixepoch()
WHERE id = ?
RETURNING id, days_of_week, start_minute, end_minute, status_emoji, status_text, presence, priority, created_at, updated_at
`

type UpdateScheduleRuleParams struct {
	DaysOfWeek  int64
	StartMinute int64
	EndMinute   int64
	StatusEmoji string
	StatusText  string
	Presence    string
	Priority    int64
	ID          int64
}

func (q *Queries) UpdateScheduleRule(ctx context.Context, arg UpdateScheduleRuleParams) (ScheduleRule, error) {
	row := q.db.QueryRowContext(ctx, updateScheduleRule,
		arg.DaysOfWeek,
		arg.StartMinute,
		arg.EndMinute,
		arg.StatusEmoji,
		arg.StatusText,
		arg.Presence,
		arg.Priority,
		arg.ID,
	)
	var i ScheduleRule
	err := row.Scan(
		&i.ID,
		&i.DaysOfWeek,
		&i.StartMinute,
		&i.EndMinute,
		&i.StatusEmoji,
		&i.StatusText,
		&i.Presence,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
